### PR TITLE
Update GAConstructor.coffee

### PR DESCRIPTION
**Pull request by kkateivanova**
Upgrade to analytics.js

### CODE REVIEW

**Comment by lexich** [comment]
@maximkoretskiy Please check this PR

**Comment by maximkoretskiy** [comment]
Ok. I ll look at this code tommorow

**Comment by maximkoretskiy** [comment]
@kkateivanova Why did U removed this fragment?
```coffee
      if @isUniversal
        (if isSecure then 'https://' else 'http://') + 'stats.g.doubleclick.net/dc.js'
```

**Comment by kkateivanova** [comment]
@maximkoretskiy Because analytics.js is universal and can replace dc.js and ga.js both
According to https://developers.google.com/analytics/devguides/collection/upgrade/reference/gajs-analyticsjs I added this fragment for dc.js replacement case
```
    ga('require', 'displayfeatures') if displayfeatures
```

**Comment by maximkoretskiy** [comment]
All is fine. Now you should build all project files with `grunt build`. Dont forget to bump project version(`package.json`, `bower.json`) @kkateivanova

**Comment by lexich** [comment]
@kkateivanova Now update to version 0.0.9

**Comment by maximkoretskiy** [comment]
@kkateivanova :+1:

**Comment by kkateivanova** [comment]
@lexich @maximkoretskiy Cool, thank you:+1:

**Pull request merged**
